/*
 *
 * App constants
 *
 */


export const APP_START = `APP_START`;
export const APP_SUCCESS = `APP_SUCCESS`;
export const APP_ERROR = `APP_ERROR`;

export const FETCH_PRODUCT_LIST_START = `FETCH_PRODUCT_LIST_START`;
export const FETCH_PRODUCT_LIST_SUCCESS = `FETCH_PRODUCT_LIST_SUCCESS`;
export const FETCH_PRODUCT_LIST_ERROR = `FETCH_PRODUCT_LIST_ERROR`;

export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_SELECTED_CATEGORIES = 'SET_SELECTED_CATEGORIES';